from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, TypedDict


# -------------------------
# Core domain entities
# -------------------------

@dataclass(frozen=True)
class User:
    """
    Represents a single logical user across platforms.
    """
    id: int
    discord_user_id: str | None
    telegram_user_id: str | None
    display_name: str | None
    created_at: str  # sqlite datetime string


@dataclass(frozen=True)
class BeanAccount:
    user_id: int
    balance: int
    updated_at: str  # sqlite datetime string


@dataclass(frozen=True)
class BeanTransaction:
    id: int
    user_id: int
    delta: int
    reason: str
    game_key: str | None
    metadata_json: str | None
    created_at: str  # sqlite datetime string


@dataclass(frozen=True)
class GameResult:
    id: int
    user_id: int
    game_key: str
    score: int | None
    beans_earned: int
    context_json: str | None
    created_at: str  # sqlite datetime string


# -------------------------
# Leaderboard / view models
# -------------------------

@dataclass(frozen=True)
class LeaderboardRow:
    """
    A row in the global leaderboard.
    """
    user_id: int
    display_name: str
    balance: int


@dataclass(frozen=True)
class GameStatsRow:
    """
    Optional: per-game breakdown (for #game-stats).
    """
    game_key: str
    plays: int
    total_beans: int
    avg_score: float | None


# -------------------------
# Active session models
# -------------------------

Platform = Literal["discord", "telegram"]
SessionStatus = Literal["active", "ended", "cancelled"]


class SessionRef(TypedDict, total=False):
    """
    Identifies where a session is happening on a platform.
    Stored as strings in DB for portability.
    """
    platform: Platform
    location_id: str        # discord channel_id or telegram chat_id
    thread_id: str | None   # discord thread_id (optional)


@dataclass(frozen=True)
class ActiveGameSession:
    """
    Persisted game session for restart-safe tracking.
    State is stored as JSON (string).
    """
    id: str                 # UUID string generated by app
    platform: Platform
    location_id: str
    thread_id: str | None
    game_key: str
    status: SessionStatus
    state_json: str         # JSON string
    created_at: str
    updated_at: str
    expires_at: str | None


# -------------------------
# Utility typing helpers
# -------------------------

JSONDict = dict[str, Any]
